//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.IO;
using LumenWorks.Framework.IO.Csv;
namespace AssemblyCSharp
{
	public class CrimeData{

	public class CrimeEntry
	{
		public string shift;
		public string offense;
		public string method;
		public string ward;
		public string district;
		public string reportDate;
	}

	void ReadCsv()
	{
		Dictionary<string, int> myObjectMap = new Dictionary<string, int>();
		List<CrimeEntry> crimeList = new List<CrimeEntry> ();
			using (CsvReader csv = new CsvReader(new StreamReader("data.csv"), true)) {
				int fieldCount = csv.FieldCount;
				string[] headers = csv.GetFieldHeaders();

				for(int i = 0; i < fieldCount; i++){
					myObjectMap[headers[i]] = i;
				}
				while(csv.ReadNextRecord()){
					CrimeEntry crime = new CrimeEntry();

					crime.shift = csv[myObjectMap["SHIFT"]];
					crime.offense = csv[myObjectMap["OFFENSE"]];
					crime.method = csv[myObjectMap["METHOD"]];
					crime.ward = csv[myObjectMap["WARD"]];
					crime.district = csv[myObjectMap["DISTRICT"]];
					crime.reportDate = csv[myObjectMap["REPROTDATETIME"]];
					crimeList.Add(crime);
				}
			}
	}
	
	}

}

